-- Run in STRSQL or ACS Run SQL Scripts on Pub400.
-- Replace YOURLIB with your private library.

CREATE TABLE AYAN4001.NEWSLETTER_SUBS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY,
  EMAIL VARCHAR(254) NOT NULL,
  EMAIL_NORM VARCHAR(254) NOT NULL,
  STATUS CHAR(1) NOT NULL DEFAULT 'A',
  SOURCE VARCHAR(64),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX AYAN4001.NEWS_SUBS_UX1
  ON AYAN4001.NEWSLETTER_SUBS (EMAIL_NORM);

CREATE INDEX AYAN4001.NEWS_SUBS_IX1
  ON AYAN4001.NEWSLETTER_SUBS (CREATED_AT);

-- Example minimum authority grant to service user.
-- Replace NEWSBRGUSR with your service profile.
GRANT SELECT, INSERT, UPDATE
  ON AYAN4001.NEWSLETTER_SUBS
  TO USER AYAN400;
